### PR TITLE
Idea191.x mutcianm

### PR DESCRIPTION
**Pull request by mutcianm**
- remove unused sbt plugin
- create runner project with an sbt-idea-plugin utility method
- add other IntellJ platform products comatibility - [link](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html)

### CODE REVIEW

**Comment by mutcianm** [comment]
This PR also resolves #2

**Comment by ghik** [comment]
Can we rename `master` as `idea183.x` and make `idea191.x` the default branch to mimic branching strategy of `intellij-scala`?

**Comment by mutcianm** [comment]
Yep, good idea. Could you do this after merging the pr?

**Comment by ghik** [comment]
Sure, do you want me to merge?

**Comment by mutcianm** [comment]
If it's fine by you

**Comment by ghik** [comment]
@mutcianm looks like I only have push privileges but I'm not an administrator so I can't change the default branch

**Comment by mutcianm** [comment]
Fixed the permissions

**Pull request merged**
